package com.uxl.sites.pyfia.model.db;

// Generated Jun 30, 2013 12:13:50 PM by Hibernate Tools 3.4.0.CR1

/**
 * DfinCorr generated by hbm2java
 */
public class DfinCorr implements java.io.Serializable {

	private DfinCorrId id;

	public DfinCorr() {
	}

	public DfinCorr(DfinCorrId id) {
		this.id = id;
	}

	public DfinCorrId getId() {
		return this.id;
	}

	public void setId(DfinCorrId id) {
		this.id = id;
	}

}
