package com.uxl.sites.pyfia.model.db;

// Generated Jun 30, 2013 12:13:50 PM by Hibernate Tools 3.4.0.CR1

/**
 * UsersAttrId generated by hbm2java
 */
public class UsersAttrId implements java.io.Serializable {

	private String login;
	private String name;
	private String val;

	public UsersAttrId() {
	}

	public UsersAttrId(String login, String name, String val) {
		this.login = login;
		this.name = name;
		this.val = val;
	}

	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getVal() {
		return this.val;
	}

	public void setVal(String val) {
		this.val = val;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UsersAttrId))
			return false;
		UsersAttrId castOther = (UsersAttrId) other;

		return ((this.getLogin() == castOther.getLogin()) || (this.getLogin() != null
				&& castOther.getLogin() != null && this.getLogin().equals(
				castOther.getLogin())))
				&& ((this.getName() == castOther.getName()) || (this.getName() != null
						&& castOther.getName() != null && this.getName()
						.equals(castOther.getName())))
				&& ((this.getVal() == castOther.getVal()) || (this.getVal() != null
						&& castOther.getVal() != null && this.getVal().equals(
						castOther.getVal())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getLogin() == null ? 0 : this.getLogin().hashCode());
		result = 37 * result
				+ (getName() == null ? 0 : this.getName().hashCode());
		result = 37 * result
				+ (getVal() == null ? 0 : this.getVal().hashCode());
		return result;
	}

}
