package com.uxl.sites.pyfia.model.db;

// Generated Jun 30, 2013 12:13:50 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	private String login;
	private String password;
	private Set usersAttrs = new HashSet(0);

	public Users() {
	}

	public Users(String login, String password) {
		this.login = login;
		this.password = password;
	}

	public Users(String login, String password, Set usersAttrs) {
		this.login = login;
		this.password = password;
		this.usersAttrs = usersAttrs;
	}

	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Set getUsersAttrs() {
		return this.usersAttrs;
	}

	public void setUsersAttrs(Set usersAttrs) {
		this.usersAttrs = usersAttrs;
	}

}
