package com.uxl.sites.pyfia.model.db;

// Generated Jun 30, 2013 12:13:50 PM by Hibernate Tools 3.4.0.CR1

/**
 * UsersAttr generated by hbm2java
 */
public class UsersAttr implements java.io.Serializable {

	private UsersAttrId id;
	private Users users;

	public UsersAttr() {
	}

	public UsersAttr(UsersAttrId id, Users users) {
		this.id = id;
		this.users = users;
	}

	public UsersAttrId getId() {
		return this.id;
	}

	public void setId(UsersAttrId id) {
		this.id = id;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

}
